// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaddockAPI.Infrastructure.Database;

#nullable disable

namespace Paddock.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260425130933_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Constructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasJsonPropertyName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LocationId")
                        .HasColumnType("int")
                        .HasJsonPropertyName("locationId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasJsonPropertyName("name");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasJsonPropertyName("nationality");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Constructors");

                    b.HasAnnotation("Relational:JsonPropertyName", "constructor");
                });

            modelBuilder.Entity("Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasJsonPropertyName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasJsonPropertyName("code");

                    b.Property<int>("ConstructorId")
                        .HasColumnType("int")
                        .HasJsonPropertyName("constructorId");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2")
                        .HasJsonPropertyName("dateOfBirth");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasJsonPropertyName("firstname");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasJsonPropertyName("lastname");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasJsonPropertyName("nationality");

                    b.Property<int?>("Number")
                        .HasColumnType("int")
                        .HasJsonPropertyName("number");

                    b.HasKey("Id");

                    b.HasIndex("ConstructorId");

                    b.ToTable("Drivers");

                    b.HasAnnotation("Relational:JsonPropertyName", "driver");
                });

            modelBuilder.Entity("Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasJsonPropertyName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasJsonPropertyName("country");

                    b.Property<double>("Latitude")
                        .HasColumnType("float")
                        .HasJsonPropertyName("latitude");

                    b.Property<string>("Locality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasJsonPropertyName("locality");

                    b.Property<double>("Longitude")
                        .HasColumnType("float")
                        .HasJsonPropertyName("longitude");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasAnnotation("Relational:JsonPropertyName", "location");
                });

            modelBuilder.Entity("PointByPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasJsonPropertyName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Place")
                        .HasColumnType("int")
                        .HasJsonPropertyName("place");

                    b.Property<double>("Points")
                        .HasColumnType("float")
                        .HasJsonPropertyName("points");

                    b.Property<int>("SeasonYear")
                        .HasColumnType("int")
                        .HasJsonPropertyName("seasonYear");

                    b.HasKey("Id");

                    b.HasIndex("SeasonYear");

                    b.ToTable("PointByPositions");
                });

            modelBuilder.Entity("Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasJsonPropertyName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DriverId")
                        .HasColumnType("int")
                        .HasJsonPropertyName("driverId");

                    b.Property<int>("FinishGrid")
                        .HasColumnType("int")
                        .HasJsonPropertyName("finishGrid");

                    b.Property<bool>("IsFastestLap")
                        .HasColumnType("bit")
                        .HasJsonPropertyName("fastestLap");

                    b.Property<double>("Points")
                        .HasColumnType("float")
                        .HasJsonPropertyName("points");

                    b.Property<int>("RaceId")
                        .HasColumnType("int")
                        .HasJsonPropertyName("raceId");

                    b.Property<int?>("RaceId1")
                        .HasColumnType("int");

                    b.Property<int>("StartingGrid")
                        .HasColumnType("int")
                        .HasJsonPropertyName("startingGrid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("status");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("time");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("RaceId");

                    b.HasIndex("RaceId1");

                    b.ToTable("Positions");

                    b.HasAnnotation("Relational:JsonPropertyName", "positions");
                });

            modelBuilder.Entity("Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasJsonPropertyName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasJsonPropertyName("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasJsonPropertyName("name");

                    b.Property<int>("Round")
                        .HasColumnType("int")
                        .HasJsonPropertyName("round");

                    b.Property<int>("SeasonYear")
                        .HasColumnType("int")
                        .HasJsonPropertyName("seasonYear");

                    b.Property<int>("TrackId")
                        .HasColumnType("int")
                        .HasJsonPropertyName("trackId");

                    b.HasKey("Id");

                    b.HasIndex("SeasonYear");

                    b.HasIndex("TrackId");

                    b.ToTable("Races");

                    b.HasAnnotation("Relational:JsonPropertyName", "races");
                });

            modelBuilder.Entity("Season", b =>
                {
                    b.Property<int>("Year")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasJsonPropertyName("year");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Year"));

                    b.HasKey("Year");

                    b.ToTable("Seasons");

                    b.HasAnnotation("Relational:JsonPropertyName", "season");
                });

            modelBuilder.Entity("StandingConstructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasJsonPropertyName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConstructorId")
                        .HasColumnType("int")
                        .HasJsonPropertyName("constructorId");

                    b.Property<double>("Points")
                        .HasColumnType("float")
                        .HasJsonPropertyName("points");

                    b.Property<int?>("RaceId")
                        .HasColumnType("int");

                    b.Property<int>("Rank")
                        .HasColumnType("int")
                        .HasJsonPropertyName("rank");

                    b.Property<int>("SeasonYear")
                        .HasColumnType("int")
                        .HasJsonPropertyName("seasonYear");

                    b.Property<int>("Wins")
                        .HasColumnType("int")
                        .HasJsonPropertyName("wins");

                    b.HasKey("Id");

                    b.HasIndex("ConstructorId");

                    b.HasIndex("RaceId");

                    b.HasIndex("SeasonYear");

                    b.ToTable("StandingConstructors");

                    b.HasAnnotation("Relational:JsonPropertyName", "standingsConstructors");
                });

            modelBuilder.Entity("StandingDriver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasJsonPropertyName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DriverId")
                        .HasColumnType("int")
                        .HasJsonPropertyName("driverId");

                    b.Property<double>("Points")
                        .HasColumnType("float")
                        .HasJsonPropertyName("points");

                    b.Property<int?>("RaceId")
                        .HasColumnType("int");

                    b.Property<int>("Rank")
                        .HasColumnType("int")
                        .HasJsonPropertyName("rank");

                    b.Property<int>("SeasonYear")
                        .HasColumnType("int")
                        .HasJsonPropertyName("seasonYear");

                    b.Property<int>("Wins")
                        .HasColumnType("int")
                        .HasJsonPropertyName("wins");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("RaceId");

                    b.HasIndex("SeasonYear");

                    b.ToTable("StandingDrivers");

                    b.HasAnnotation("Relational:JsonPropertyName", "standingsDrivers");
                });

            modelBuilder.Entity("Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasJsonPropertyName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LocationId")
                        .HasColumnType("int")
                        .HasJsonPropertyName("locationId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasJsonPropertyName("name");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Tracks");

                    b.HasAnnotation("Relational:JsonPropertyName", "track");
                });

            modelBuilder.Entity("Constructor", b =>
                {
                    b.HasOne("Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Driver", b =>
                {
                    b.HasOne("Constructor", "Constructor")
                        .WithMany()
                        .HasForeignKey("ConstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Constructor");
                });

            modelBuilder.Entity("PointByPosition", b =>
                {
                    b.HasOne("Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonYear")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("Position", b =>
                {
                    b.HasOne("Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Race", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Race", null)
                        .WithMany("Positions")
                        .HasForeignKey("RaceId1");

                    b.Navigation("Driver");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("Race", b =>
                {
                    b.HasOne("Season", "Season")
                        .WithMany("Races")
                        .HasForeignKey("SeasonYear")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Track", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("StandingConstructor", b =>
                {
                    b.HasOne("Constructor", "Constructor")
                        .WithMany()
                        .HasForeignKey("ConstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Race", null)
                        .WithMany("StandingsConstructors")
                        .HasForeignKey("RaceId");

                    b.HasOne("Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonYear")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Constructor");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("StandingDriver", b =>
                {
                    b.HasOne("Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Race", null)
                        .WithMany("StandingsDrivers")
                        .HasForeignKey("RaceId");

                    b.HasOne("Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonYear")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("Track", b =>
                {
                    b.HasOne("Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Race", b =>
                {
                    b.Navigation("Positions");

                    b.Navigation("StandingsConstructors");

                    b.Navigation("StandingsDrivers");
                });

            modelBuilder.Entity("Season", b =>
                {
                    b.Navigation("Races");
                });
#pragma warning restore 612, 618
        }
    }
}
